# Generated by Django 5.1.3 on 2025-02-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('dp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dp_date', models.DateField()),
                ('dp_created_date', models.DateField(blank=True, null=True)),
                ('dp_last_updated', models.DateField(blank=True, null=True)),
                ('dp_open', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dp_high', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dp_low', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dp_close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dp_adj_close', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dp_volume', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exchange_id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_name', models.CharField(max_length=50)),
                ('exchange_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_created_date', models.DateField(blank=True, null=True)),
                ('exchange_last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'portfolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('security_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_ticker', models.CharField(max_length=10)),
                ('security_name', models.CharField(max_length=50)),
                ('security_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('security_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('security_created_date', models.DateField(blank=True, null=True)),
                ('security_last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioSecurity',
            fields=[
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.portfolio')),
                ('portfolio_security_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'portfolio_security',
                'managed': False,
            },
        ),
    ]
