# Generated by Django 5.1.3 on 2025-03-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userfavouritesecurities_security_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'managed': True},
        ),
    ]
