# Generated by Django 5.1.3 on 2025-03-07 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_portfolio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosecurity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
